# Generated by Django 5.1.6 on 2025-03-31 17:40

import django.core.validators
import django.db.models.deletion
import texts_storage.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.FileField(upload_to=texts_storage.models.user_directory_path, validators=[django.core.validators.FileExtensionValidator(['html'])])),
                ('title', models.CharField(max_length=255, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Many_Words',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_start_word', models.IntegerField()),
                ('id_end_word', models.IntegerField()),
                ('words', models.CharField(max_length=255)),
                ('transl', models.CharField(max_length=255)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='texts_storage.articles')),
            ],
        ),
        migrations.CreateModel(
            name='Words',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_word', models.IntegerField()),
                ('word', models.CharField(max_length=255)),
                ('transl', models.CharField(max_length=255)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='texts_storage.articles')),
            ],
        ),
    ]
