# Generated by Django 5.1.6 on 2025-03-19 21:22

import django.core.validators
import django.db.models.deletion
import texts_storage.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Texts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.FileField(upload_to=texts_storage.models.user_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['txt'])])),
                ('title', models.CharField(max_length=255, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
