# Generated by Django 5.1.6 on 2025-03-19 21:28

import django.core.validators
import texts_storage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texts_storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='texts',
            name='text',
            field=models.FileField(upload_to=texts_storage.models.user_directory_path, validators=[django.core.validators.FileExtensionValidator(['txt'])]),
        ),
    ]
