# Generated by Django 5.1.6 on 2025-03-20 12:02

import django.core.validators
import django.db.models.deletion
import texts_storage.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texts_storage', '0003_alter_texts_text'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.FileField(upload_to=texts_storage.models.user_directory_path, validators=[django.core.validators.FileExtensionValidator(['html'])])),
                ('title', models.CharField(max_length=255, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Texts',
        ),
    ]
